### ISSUE TITLE
The entrypoint script doesn't exit at Node process error

### ISSUE THREAD

**Issue by solsson** [Yolean/kafka-transform-nodejs-runtime#2]
Just logging this because I don't have the capacity to troubleshoot atm.

Due to some weird caching `build-contract` seems to start an old build, with a non-existent handler. This seems to reveal that the container doesn't exit on an error like

```
sample-function-1_1    | internal/modules/cjs/loader.js:583
sample-function-1_1    |     throw err;
sample-function-1_1    |     ^
sample-function-1_1    | 
sample-function-1_1    | Error: Cannot find module './handler'
sample-function-1_1    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
sample-function-1_1    |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
sample-function-1_1    |     at Module.require (internal/modules/cjs/loader.js:637:17)
sample-function-1_1    |     at require (internal/modules/cjs/helpers.js:22:18)
sample-function-1_1    |     at Object.<anonymous> (/usr/src/runtime/index.js:2:17)
sample-function-1_1    |     at Module._compile (internal/modules/cjs/loader.js:689:30)
sample-function-1_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
sample-function-1_1    |     at Module.load (internal/modules/cjs/loader.js:599:32)
sample-function-1_1    |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
sample-function-1_1    |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Of course that might be because the build isn't running the current source.

**Comment by solsson** [comment]
The error was fixed in https://github.com/Yolean/kafka-transform-nodejs-runtime/commit/a03327a77192ececcf6f85de8648eafa58ce6fcd, but I think the issue remains.

**Comment by solsson** [comment]
Actually the hang is almost a feature now. We'll lose only one message in case of handler errors, instead of the rest of the queue as we would if the pod restarted.
